import type { Metadata } from "next";
import { Inter } from "next/font/google"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Visual Stack with HandTracking",
  description: "Generated by Ritsuki Ishikawa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
          <Header className="h-[10vh]" />
          <main className="flex-grow h-[80vh]">{children}</main>
          <Footer className="h-[10vh]" />
        </div>
      </body>
    </html>
  );
}
